blank_issues_enabled: true
contact_links:
  - name: Unmet Hours
    url: https://unmethours.com
    about: "Ask modeling **questions** on unmethours.com"
  - name: Helpdesk
    url: https://energyplushelp.freshdesk.com/support/home
    about: The helpdesk can also help you
